language: node_js
node_js:
  - "0.11"
  - "0.10"
services:
  - mongodb
before:
  - npm install -g istanbul
  - npm install -g mocha
after_success:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec --recursive
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - rm -rf ./coverage